"""Create models

Revision ID: 1ae09afa580a
Revises: 
Create Date: 2023-01-27 13:47:35.671529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ae09afa580a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consistency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('each', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('hour', 'day', 'week', 'month', 'year', name='consistency_types'), nullable=True),
    sa.Column('sunday', sa.Boolean(), nullable=True),
    sa.Column('monday', sa.Boolean(), nullable=True),
    sa.Column('tuesday', sa.Boolean(), nullable=True),
    sa.Column('wednesday', sa.Boolean(), nullable=True),
    sa.Column('thursday', sa.Boolean(), nullable=True),
    sa.Column('friday', sa.Boolean(), nullable=True),
    sa.Column('saturday', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('habit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fire_at', sa.TIME(), nullable=False),
    sa.Column('habit_start', sa.DATE(), nullable=False),
    sa.Column('repeat_times', sa.Integer(), nullable=True),
    sa.Column('habit_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['consistency.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habit_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('XP_change', sa.Integer(), nullable=True),
    sa.Column('done_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habit_tracks')
    op.drop_table('habit')
    op.drop_table('user')
    op.drop_table('consistency')
    # ### end Alembic commands ###
